# Change these first
owner: kyryl-bogach # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: kyryl.bogach.es
    url: https://kyryl.bogach.es
  - name: reservas.mudic.es
    url: https://reservas.mudic.es
  - name: clinicafabregat.com
    url: https://clinicafabregat.com
  - name: senoshaidodelasmanos.bogach.es
    url: https://senoshaidodelasmanos.bogach.es/
  - name: admin.angelopezdietista.com
    url: https://admin.angelopezdietista.com
  - name: grazindafranco.com
    url: https://grazindafranco.com
  - name: mail.bogach.es
    url: https://mail.bogach.es
    
assignees:
  - kyryl-bogach

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bogach.es
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
